name: domain
description: A new Flutter project.
version: 0.0.1
homepage: https://github.com/Dennis-Mwea
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  injectable: ^1.4.1
  freezed:
  dio: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6
  injectable_generator: ^1.4.1
  freezed_annotation:

flutter:
